# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pchambon <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/08 15:58:00 by pchambon          #+#    #+#              #
#    Updated: 2018/11/08 16:32:49 by pchambon         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

Name=display_file.c

all: compile

compile:
	gcc -Wextra -Werror -Wall -o ft_display_file $(Name)

clean:
	/bin/rm -f *.o


fclean: clean
	/bin/rm -f ft_display_file
re: fclean all
